services:
  - type: web
    name: smart-converter-hub
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Homepage.py --server.port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10